### ISSUE TITLE
Overrides default mac binding

### ISSUE THREAD

**Issue by fredcallaway** [mghweb/SublimeTabr#2]
By default, `super+shift+t` is bound to `reopen_last_file`. It would be better to use a mac binding that isn't used by the sublime default key bindings, for example `super+shit+alt+t`.

(Great plugin by the way!)

**Comment by mghdotdev** [comment]
Hello,

I am glad you're liking the plugin!

Thank you for the suggestion and I have changed the keybinding to `super+shift+alt+t`. I have pushed out an update and it should be available soon!

**Comment by princemaple** [comment]
@mghweb great plugin! Maybe update your readme to reflect the change?

**Comment by mghdotdev** [comment]
The Readme has been updated.

Thanks!
